spring:
  datasource:
    username: root
    password: backend
    url: jdbc:mysql://${DB_SERVER:localhost}:3306/bug_tracker
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      # generate SQL statements
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              create-target: init-mysql-db.sql
#              drop-target: init-mysql-db.sql
    hibernate:
      ddl-auto: validate
  driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true